version: 1.2
workflows:
  - subclass: Nextflow
    name: cocci-call
    primaryDescriptorPath: /main.nf
    descriptorType: NFL
    gitUrl: https://github.com/Cedson3459/cocci-call.git
    defaultVersion: v1.0.0
